# Pandas Assignment - Data Cleaning

Easy to Moderate Level

## Q1. Find Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Riya",None],
    "Age":[21,np.nan,25]
})

Output:
    Name    Age
0  False  False
1  False   True
2   True  False

In [3]:
# Write your code here
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Name":["Aman","Riya",None],
    "Age":[21,np.nan,25]
})
df.isnull()

    Name    Age
0  False  False
1  False   True
2   True  False

## Q2. Count Total Missing Values

Input:
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,None,25]
})

Output:
Name    1
Age     1

In [5]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman",None,"Raj"],
    "Age":[20,None,25]
})
df.isnull().sum()

Name    1
Age     1
dtype: int64

## Q3. Fill Missing Age with 0

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,None]
})

Output:
   Name   Age
0  Aman  20.0
1   Raj   0.0

In [7]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "Age":[20,None]
})
df = df.fillna(0)
df

   Name   Age
0  Aman  20.0
1   Raj   0.0

## Q4. Fill Missing City with 'Unknown'

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal",None]
})

Output:
   Name     City
0  Aman   Bhopal
1   Raj  Unknown

In [8]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal",None]
})
df = df.fillna('Unknown')
df

   Name     City
0  Aman   Bhopal
1   Raj  Unknown

## Q5. Remove Rows Having Null Values

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})

Output:
   Name  Age
0  Aman   20
1   Raj   25

In [10]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj",None],
    "Age":[20,25,30]
})
#removes rows having null value
df = df.dropna()
df

   Name  Age
0  Aman   20
1   Raj   25

## Q6. Convert Age Column into Float

Input:
df = pd.DataFrame({"Age":[20,25,30]})

Output:
20.0, 25.0, 30.0

In [11]:
# Write your code here
df = pd.DataFrame({
    "Age":[20,25,30]
})
df['Age'] = df['Age'].astype(float)
df

    Age
0  20.0
1  25.0
2  30.0

## Q7. Replace Delhi with New Delhi

Input:
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})

Output:
New Delhi, Mumbai, New Delhi

In [13]:
# Write your code here
df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi"]
})
df['City'] = df["City"].replace('Delhi', 'New Delhi')
df

        City
0  New Delhi
1     Mumbai
2  New Delhi

## Q8. Replace Score 88 with 100

Input:
df = pd.DataFrame({
    "Score":[88,90,88,75]
})

Output:
100,90,100,75

In [14]:
# Write your code here
df = pd.DataFrame({
    "Score":[88,90,88,75]
})
df.Score = df.Score.replace(88, 100)
df

   Score
0    100
1     90
2    100
3     75

## Q9. Drop City Column

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal","Indore"]
})

Output:
   Name
0  Aman
1   Raj

In [18]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj"],
    "City":["Bhopal","Indore"]
})
#for cols removal in df
df.drop('City',axis=1, inplace=True)
df

   Name
0  Aman
1   Raj

## Q10. Drop Row at Index 1

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Riya"]
})

Output:
   Name
0  Aman
2  Riya

In [20]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj","Riya"]
})
df.drop(index=1, axis=0, inplace=True)
df

   Name
0  Aman
2  Riya

## Q11. Check Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
False, False, True

In [ ]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})
#used to find the duplicate value in df 
print(df.duplicated())

0    False
1    False
2     True
dtype: bool

## Q12. Remove Duplicate Rows

Input:
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})

Output:
   Name
0  Aman
1   Raj

In [25]:
# Write your code here
df = pd.DataFrame({
    "Name":["Aman","Raj","Aman"]
})
df.drop_duplicates(inplace=True, keep='first')
print(df)

   Name
0  Aman
1   Raj

## Q13. Mini Data Cleaning Task

Input:
data = {
    "Name":["Aman","Raj","Aman",None],
    "Age":[20,None,20,25],
    "City":["Bhopal","Delhi","Bhopal","Indore"]
}

Task:
1. Fill missing Age with mean.
2. Remove duplicate rows.
3. Display final DataFrame.

In [28]:
# Write your code here
data = {
    "Name":["Aman","Raj","Aman",None],
    "Age":[20,None,20,25],
    "City":["Bhopal","Delhi","Bhopal","Indore"]
}
df = pd.DataFrame(data)

#filling age with mean value
df['Age'] = df["Age"].fillna(df.Age.mean())

#filling null name with unknown
df['Name'] = df["Name"].fillna('Unknown')

#removing duplicate rows
df.drop_duplicates(inplace=True, keep='first')

#final dataframe
df

      Name        Age    City
0     Aman  20.000000  Bhopal
1      Raj  21.666667   Delhi
3  Unknown  25.000000  Indore